version: '3.8'

services:
  podsite-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - GO_ENV=development
      - PORT=3001
      - LOG_LEVEL=debug
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8080
    volumes:
      # Mount content files for development
      - ../frontend/site/content:/app/content:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - podsite-network

networks:
  podsite-network:
    driver: bridge
