name: Backend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths: 
      - 'app/backend/**'
      - 'specs/backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main ]
    paths: 
      - 'app/backend/**'
      - 'specs/backend/**'
      - '.github/workflows/backend-ci.yml'

defaults:
  run:
    working-directory: app/backend

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go-version: [1.21.x, 1.22.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        cache-dependency-path: app/backend/go.sum
        
    - name: Download dependencies
      run: make deps
      
    - name: Run linting
      run: make lint
      
    - name: Run tests
      run: make test
      
    - name: Run tests with coverage
      run: make test-coverage
      
    - name: Run tests with race detection
      run: make test-race

  docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: make docker-build
      
    - name: Test Docker image
      run: |
        docker run -d --name test-backend -p 3001:3001 podsite-backend
        sleep 10
        curl -f http://localhost:3001/health || exit 1
        docker stop test-backend
        docker rm test-backend

  deploy:
    runs-on: ubuntu-latest
    needs: [test, docker]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./app/backend
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/podsite-backend:latest
          ${{ secrets.DOCKER_USERNAME }}/podsite-backend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
      
    # Add deployment steps here (e.g., to Heroku, AWS, etc.)
    - name: Deploy to production
      run: echo "Add deployment script here"
